name: googledrive_dm
description: Google Drive と連携したファイル管理アプリ
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: any
  googleapis: any
  provider: any
  shared_preferences: any
  http: any
  googleapis_auth: any
  url_launcher: ^6.3.1
  shelf: any
  crypto: any
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true